document.writeln("    <div class=\"footer-content\">")
document.writeln("    	<p><a href=\"http://www.neu.edu.cn\">东北大学<a></p>")
document.writeln("    	<p><a href=\"http://www.graduate.neu.edu.cn\">研究生院<a></p>")
document.writeln("    	<p><a href=\"http://www.cse.neu.edu.cn\">计算机科学与工程学院</a></p>")
document.writeln("    </div>")
document.writeln("    <div class=\"footer-content\">")	
document.writeln("    	<p>联系电话：+86-024-83672602</p>")
document.writeln("    	<p>联系地址：辽宁省沈阳市浑南区 东北大学浑南校区 信息馆</p>")
document.writeln("    </div>")
document.writeln("    <p style=\"font-size:14px\">Copyright 2021 NEU iDC Group. All rights reserved.</p>")
document.writeln("    </br>")