document.writeln("    <div class=\"logo\"><h1>分布式智能计算系统课题组</h1></div>")
document.writeln("    		<a class=\"menu_trigger\" href=\"#\"></a>")
document.writeln("    		<nav id=\"nav\">")
document.writeln("    			<ul>")
document.writeln("    				<li><a href=\"index.html\">主页</a></li>")
document.writeln("   				<li><a href=\"publications.html\">发表论文</a></li>")
document.writeln("   				<li><a href=\"research.html\">研究方向</a></li>")
document.writeln("   				<li><a href=\"project.html\">科研项目</a></li>")
document.writeln("    				<li><a href=\"member.html\">团队成员</a></li>")
document.writeln("    				<li><a href=\"news_actives.html\">新闻活动</a></li>	")						
document.writeln("    				<li><a href=\"index_en.html\">English</a></li>")
document.writeln("    			</ul>")
document.writeln("    		</nav>")